version: "3.8"

services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://root:password@postgres-db
    depends_on:
      - postgres-db
    container_name: restaurant_api

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant_api_development
    volumes:
      - postgres-db:/var/lib/postgresql/data
    container_name: postgres_db

volumes:
  postgres-db:
