services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres-db
    depends_on:
      - postgres-db
    container_name: restaurant_api

  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: restaurant_api_development
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    container_name: postgres_db

volumes:
  postgres-db:
